name: Test
on: [push, pull_request]

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Test action
    steps:
      - uses: actions/checkout@v1

      - name: Run action action
        id: var
        uses: ./
        with:
          owner: 'scoutbeedev'
          repo: 'react-intelligence'
          event: 'workflow_dispatch'
          name: 'Deploy to production'
          GITHUB_AUTH_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}

      - name: Get action output
        run: echo "${{ steps.var.outputs.data }}"
