name: Test
on: [push, pull_request, workflow_dispatch]

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Test action
    steps:
      - uses: actions/checkout@v1

      - name: Run action action
        id: var
        uses: ./
        with:
          owner: 'scoutbeedev'
          repo: 'react-intelligence'
          event: 'workflow_dispatch'
          name: 'Deploy to production'
          GITHUB_AUTH_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}

      - name: Get action output
        run: echo "${{ fromJson(steps.var.outputs.data).head_branch }}"

      - name: Cut changelog
        id: changelog
        run: |
          CHANGELOG=$(cat CHANGELOG.md | sed -n '/v2.3.3/,/v2.2.0/p')
          echo "::set-output name=CHANGELOG::$CHANGELOG"

      - name: Send Slack release message
        uses: archive/github-actions-slack@master
        id: send-message
        with:
          slack-function: send-message
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel: bot-test-channel
          slack-text: ${{ steps.changelog.outputs.CHANGELOG }}
