name: Test
on: [push, pull_request, workflow_dispatch]

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Test action
    steps:
      - uses: actions/checkout@v1

      - name: Run action action
        id: var
        uses: ./
        with:
          owner: 'scoutbeedev'
          repo: 'react-intelligence'
          event: 'workflow_dispatch'
          name: 'Deploy to production'
          GITHUB_AUTH_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}

      - name: Get action output
        run: echo "${{ fromJson(steps.var.outputs.data).head_branch }}"

      - name: Get changelog
        id: changelog
        run: |
          CHANGELOG=$(sed -n '/v2.3.3/,/v2.2.0/p' CHANGELOG.md)
          CHANGELOG="${CHANGELOG//'%'/'%25'}"
          CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
          CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
          echo "::set-output name=content::$CHANGELOG"

      - name: Slack Markdown Converter
        id: slack-md-converter
        uses: LoveToKnow/slackify-markdown-action@v1.0.0
        with:
          text: ${{ steps.changelog.outputs.content }}

      - name: Send Slack release message
        uses: archive/github-actions-slack@master
        id: send-message
        with:
          slack-function: send-message
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel: bot-test-channel
          slack-text: 'Intelligence was deployed to production. \n Release notes are in thread.'
